In [11]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import re
import datetime as dt
from scripts import pumpitup

from scipy import stats

from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import KFold

sns.set_style("white")
sns.set_context("talk")

%matplotlib inline

In [26]:
df = pd.read_csv('data/training_set.csv')

In [87]:
train_funder = train_data['funder']
value_counts = train_funder.value_counts()
to_remove = value_counts[value_counts <= 0.0084 * len(train_funder)].index
train_funder.replace(to_remove, 'other', inplace=True)

test_funder = test_data['funder']
value_counts = test_funder.value_counts()
to_remove = value_counts[value_counts <= 0.0084 * len(test_funder)].index
test_funder.replace(to_remove, 'other', inplace=True)

In [88]:
train_funder.value_counts()

other                     26939
Government Of Tanzania     9084
Danida                     3114
Hesawa                     2202
Rwssp                      1374
World Bank                 1349
Kkkt                       1287
World Vision               1246
Unicef                     1057
Tasaf                       877
District Council            843
Dhv                         829
Private Individual          826
Dwsp                        811
0                           777
Norad                       765
Germany Republi             610
Tcrs                        602
Ministry Of Water           590
Water                       583
Name: funder, dtype: int64

In [54]:
mask = df['funder'].isin(['Danida']).tolist()
mask = [not val for val in mask]

In [56]:
df['funder'][mask]

0                           Roman
1                         Grumeti
2                    Lottery Club
3                          Unicef
4                     Action In A
5             Mkinga Distric Coun
6                            Dwsp
7                           Rwssp
8                        Wateraid
9                     Isingiro Ho
10                        Private
12                   World Vision
13        Lawatefuka Water Supply
14                          Biore
15                          Rudep
16                         Unicef
17                         Unicef
18                         Hesawa
20                            Twe
21                           Dwsp
22                         Unicef
23                            Isf
24       African Development Bank
25         Government Of Tanzania
26                         Sobodo
27                         Hesawa
28         Government Of Tanzania
29        Lawatefuka Water Supply
30                          Water
31            

In [64]:
list1 = ['a', 'b', 'c', 'd', 'e']

In [65]:
list2 = ['e', 'd', 'a', 'c', 'b']

In [66]:
encoder1 = le.fit(list1)

In [67]:
encoder2 = le.fit(list2)

In [72]:
encoder1.classes_

array(['a', 'b', 'c', 'd', 'e'], 
      dtype='<U1')

In [73]:
encoder1.transform(list1)

array([0, 1, 2, 3, 4])

In [74]:
encoder2.transform(list1)

array([0, 1, 2, 3, 4])

In [75]:
encoder1.transform(list2)

array([4, 3, 0, 2, 1])

In [76]:
encoder2.transform(list2)

array([4, 3, 0, 2, 1])

In [77]:
import timeit

In [78]:
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

0.48782625899184495

In [79]:
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

0.36739087296882644

In [80]:
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

0.3540512230247259

In [1]:
my_dict = {'a':[1,2,3], 'b':[4,5,6]}

In [2]:
my_dict['a']

[1, 2, 3]

In [13]:
10 in pd.Series([2,5,4])

False

In [22]:
dave = True

In [23]:
not dave

False

In [24]:
dave

True